### PR TITLE
added chart changes detection

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

checks for chart changes before kind setup to save time in ci.

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for the PR. However, we should not add any Helm-specifics to this action. You can achieve what you want by only triggering a job when the charts directory has changes.

* https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-including-paths
* https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

**Comment by monotek** [comment]
Thanks for the hint :)

**Comment by scottrigby** [comment]
How is this for an option? https://github.com/helm/charts-repo-actions-demo/pull/8

**Comment by monotek** [comment]
Thanks, maybe i'll give it a try.

In the meantime i've put the chart changes detection in a separate job too, which fails and cancels Lint & Install, if no chart changes are detected.

See: https://github.com/kiwigrid/helm-charts/blob/master/.github/workflows/ci.yaml#L7

**Comment by scottrigby** [comment]
I saw that (some nice stuff in there btw!). The reason I added conditionals instead is so the job doesn't fail, even if there are no charts. Generally people will want to make add `master` branch protection, including requiring the `lint-test` status check, which this way allows.

**Pull request closed without merging**
